package commons.serviceportal.data

import de.seitenbau.serviceportal.scripting.api.v1.form.PossibleValueV1
import de.seitenbau.serviceportal.scripting.api.v1.form.PossibleValueListV1
import groovy.transform.TupleConstructor

/**
 * Helper class to access data about nations published by the "Statistisches Bundesamt" and the EU
 *
 * Data source:
 *   * https://www.destatis.de/DE/Methoden/Klassifikationen/Staat-Gebietsystematik/staatsangehoerigkeit-gebietsschluessel.html
 *     Last Update: 2023-11-02
 *     © Statistisches Bundesamt (Destatis), 2023
 *     Vervielfältigung und Verbreitung, auch auszugsweise, mit Quellennachweis gestattet.
 *     See also: https://www.destatis.de/DE/Service/Impressum/copyright-allgemein.html
 *
 *   * https://ec.europa.eu/eurostat/statistics-explained/pdfscache/4904.pdf
 */
class NationDataHelper {
  static final Set<Nation> nations = loadDb()

  /**
   * Generates a PossibleValuesList for use in Serviceportal forms from the underlying nation database
   *
   * @param valueAttribute A attribute of {@link Nation} to use as a value
   *                       (e.g. 'officialTermShort', 'continent', ...)
   * @param labelAttribute A attribute of {@link Nation} to use as a label
   *                       (e.g. 'officialTermShort', 'continent', ...)
   * @return a PossibleValuesList
   */
  static PossibleValueListV1 toPossibleValueList(String valueAttribute, String labelAttribute) {
    Set<PossibleValueV1> possibleValues = []

    nations.each { nation ->
      if (!nation.hasProperty(valueAttribute)) {
        throw new IllegalArgumentException("Cannot generate PossibleValuesList for nation as nations do not have a property called '$valueAttribute'")
      }
      if (!nation.hasProperty(labelAttribute)) {
        throw new IllegalArgumentException("Cannot generate PossibleValuesList for nation as nations do not have a property called '$labelAttribute'")
      }

      String value = nation.getProperty(valueAttribute).toString()
      String label = nation.getProperty(labelAttribute).toString()
      possibleValues.add(new PossibleValueV1(label, value, null))
    }

    possibleValues.sort { it.label }
    return new PossibleValueListV1(possibleValues)
  }

  @TupleConstructor
  static class Nation {
    String searchTerm
    String officialTermShort
    String officialTermLong
    String citizenship
    Continent continent
    String iso3166_2
    String iso3166_3
    Integer destatisBevCode
    boolean isEu
  }

  static enum Continent {
    /**
     * Africa
     */
    AFR,

    /**
     * America
     */
    AME,

    /**
     * Australia and Oceania
     */
    AOA,

    /**
     * Asia
     */
    ASI,

    /**
     * Europe
     */
    EUR
  }

  // Generated from: NationDataHelper_datasource.ods
  private final static Set<Nation> loadDb() {
    Set<Nation> nations = []

    // BEGIN Autogenerated
    nations.add(new Nation(searchTerm: "Afghanistan", officialTermShort: "Afghanistan", officialTermLong: "die Islamische Republik Afghanistan", citizenship: "afghanisch", continent: Continent.ASI, iso3166_2: "AF", iso3166_3: "AFG", destatisBevCode: Integer.parseInt("423")))
    nations.add(new Nation(searchTerm: "Ägypten", officialTermShort: "Ägypten", officialTermLong: "die Arabische Republik Ägypten", citizenship: "ägyptisch", continent: Continent.AFR, iso3166_2: "EG", iso3166_3: "EGY", destatisBevCode: Integer.parseInt("287")))
    nations.add(new Nation(searchTerm: "Albanien", officialTermShort: "Albanien", officialTermLong: "die Republik Albanien", citizenship: "albanisch", continent: Continent.EUR, iso3166_2: "AL", iso3166_3: "ALB", destatisBevCode: Integer.parseInt("121")))
    nations.add(new Nation(searchTerm: "Algerien", officialTermShort: "Algerien", officialTermLong: "die Demokratische Volksrepublik Algerien", citizenship: "algerisch", continent: Continent.AFR, iso3166_2: "DZ", iso3166_3: "DZA", destatisBevCode: Integer.parseInt("221")))
    nations.add(new Nation(searchTerm: "Andorra", officialTermShort: "Andorra", officialTermLong: "das Fürstentum Andorra", citizenship: "andorranisch", continent: Continent.EUR, iso3166_2: "AD", iso3166_3: "AND", destatisBevCode: Integer.parseInt("123")))
    nations.add(new Nation(searchTerm: "Angola", officialTermShort: "Angola", officialTermLong: "die Republik Angola", citizenship: "angolanisch", continent: Continent.AFR, iso3166_2: "AO", iso3166_3: "AGO", destatisBevCode: Integer.parseInt("223")))
    nations.add(new Nation(searchTerm: "Antigua und Barbuda", officialTermShort: "Antigua und Barbuda", officialTermLong: "Antigua und Barbuda", citizenship: "antiguanisch", continent: Continent.AME, iso3166_2: "AG", iso3166_3: "ATG", destatisBevCode: Integer.parseInt("320")))
    nations.add(new Nation(searchTerm: "Äquatorialguinea", officialTermShort: "Äquatorialguinea", officialTermLong: "die Republik Äquatorialguinea", citizenship: "äquatorialguineisch", continent: Continent.AFR, iso3166_2: "GQ", iso3166_3: "GNQ", destatisBevCode: Integer.parseInt("274")))
    nations.add(new Nation(searchTerm: "Argentinien", officialTermShort: "Argentinien", officialTermLong: "die Argentinische Republik", citizenship: "argentinisch", continent: Continent.AME, iso3166_2: "AR", iso3166_3: "ARG", destatisBevCode: Integer.parseInt("323")))
    nations.add(new Nation(searchTerm: "Armenien", officialTermShort: "Armenien", officialTermLong: "die Republik Armenien", citizenship: "armenisch", continent: Continent.ASI, iso3166_2: "AM", iso3166_3: "ARM", destatisBevCode: Integer.parseInt("422")))
    nations.add(new Nation(searchTerm: "Aserbaidschan", officialTermShort: "Aserbaidschan", officialTermLong: "die Republik Aserbaidschan", citizenship: "aserbaidschanisch", continent: Continent.ASI, iso3166_2: "AZ", iso3166_3: "AZE", destatisBevCode: Integer.parseInt("425")))
    nations.add(new Nation(searchTerm: "Äthiopien", officialTermShort: "Äthiopien", officialTermLong: "die Demokratische Bundesrepublik Äthiopien", citizenship: "äthiopisch", continent: Continent.AFR, iso3166_2: "ET", iso3166_3: "ETH", destatisBevCode: Integer.parseInt("225")))
    nations.add(new Nation(searchTerm: "Australien", officialTermShort: "Australien", officialTermLong: "Australien", citizenship: "australisch", continent: Continent.AOA, iso3166_2: "AU", iso3166_3: "AUS", destatisBevCode: Integer.parseInt("523")))
    nations.add(new Nation(searchTerm: "Bahamas", officialTermShort: "Bahamas", officialTermLong: "das Commonwealth der Bahamas", citizenship: "bahamaisch", continent: Continent.AME, iso3166_2: "BS", iso3166_3: "BHS", destatisBevCode: Integer.parseInt("324")))
    nations.add(new Nation(searchTerm: "Bahrain", officialTermShort: "Bahrain", officialTermLong: "das Königreich Bahrain", citizenship: "bahrainisch", continent: Continent.ASI, iso3166_2: "BH", iso3166_3: "BHR", destatisBevCode: Integer.parseInt("424")))
    nations.add(new Nation(searchTerm: "Bangladesch", officialTermShort: "Bangladesch", officialTermLong: "die Volksrepublik Bangladesch", citizenship: "bangladeschisch", continent: Continent.ASI, iso3166_2: "BD", iso3166_3: "BGD", destatisBevCode: Integer.parseInt("460")))
    nations.add(new Nation(searchTerm: "Barbados", officialTermShort: "Barbados", officialTermLong: "Barbados", citizenship: "barbadisch", continent: Continent.AME, iso3166_2: "BB", iso3166_3: "BRB", destatisBevCode: Integer.parseInt("322")))
    nations.add(new Nation(searchTerm: "Belarus", officialTermShort: "Belarus", officialTermLong: "die Republik Belarus", citizenship: "belarussisch", continent: Continent.EUR, iso3166_2: "BY", iso3166_3: "BLR", destatisBevCode: Integer.parseInt("169")))
    nations.add(new Nation(searchTerm: "Belgien", officialTermShort: "Belgien", officialTermLong: "das Königreich Belgien", citizenship: "belgisch", continent: Continent.EUR, iso3166_2: "BE", iso3166_3: "BEL", destatisBevCode: Integer.parseInt("124")))
    nations.add(new Nation(searchTerm: "Belize", officialTermShort: "Belize", officialTermLong: "Belize", citizenship: "belizisch", continent: Continent.AME, iso3166_2: "BZ", iso3166_3: "BLZ", destatisBevCode: Integer.parseInt("330")))
    nations.add(new Nation(searchTerm: "Benin", officialTermShort: "Benin", officialTermLong: "die Republik Benin", citizenship: "beninisch", continent: Continent.AFR, iso3166_2: "BJ", iso3166_3: "BEN", destatisBevCode: Integer.parseInt("229")))
    nations.add(new Nation(searchTerm: "Bhutan", officialTermShort: "Bhutan", officialTermLong: "das Königreich Bhutan", citizenship: "bhutanisch", continent: Continent.ASI, iso3166_2: "BT", iso3166_3: "BTN", destatisBevCode: Integer.parseInt("426")))
    nations.add(new Nation(searchTerm: "Plurinationaler Staat Bolivien", officialTermShort: "Plurinationaler Staat Bolivien", officialTermLong: "der Plurinationale Staat Bolivien", citizenship: "bolivianisch", continent: Continent.AME, iso3166_2: "BO", iso3166_3: "BOL", destatisBevCode: Integer.parseInt("326")))
    nations.add(new Nation(searchTerm: "Bosnien und Herzegowina", officialTermShort: "Bosnien und Herzegowina", officialTermLong: "Bosnien und Herzegowina", citizenship: "bosnisch-herzegowinisch", continent: Continent.EUR, iso3166_2: "BA", iso3166_3: "BIH", destatisBevCode: Integer.parseInt("122")))
    nations.add(new Nation(searchTerm: "Botsuana", officialTermShort: "Botsuana", officialTermLong: "die Republik Botsuana", citizenship: "botsuanisch", continent: Continent.AFR, iso3166_2: "BW", iso3166_3: "BWA", destatisBevCode: Integer.parseInt("227")))
    nations.add(new Nation(searchTerm: "Brasilien", officialTermShort: "Brasilien", officialTermLong: "die Föderative Republik Brasilien", citizenship: "brasilianisch", continent: Continent.AME, iso3166_2: "BR", iso3166_3: "BRA", destatisBevCode: Integer.parseInt("327")))
    nations.add(new Nation(searchTerm: "Brunei Darussalam", officialTermShort: "Brunei Darussalam", officialTermLong: "Brunei Darussalam", citizenship: "bruneiisch", continent: Continent.ASI, iso3166_2: "BN", iso3166_3: "BRN", destatisBevCode: Integer.parseInt("429")))
    nations.add(new Nation(searchTerm: "Bulgarien", officialTermShort: "Bulgarien", officialTermLong: "die Republik Bulgarien", citizenship: "bulgarisch", continent: Continent.EUR, iso3166_2: "BG", iso3166_3: "BGR", destatisBevCode: Integer.parseInt("125")))
    nations.add(new Nation(searchTerm: "Burkina Faso", officialTermShort: "Burkina Faso", officialTermLong: "Burkina Faso", citizenship: "burkinisch", continent: Continent.AFR, iso3166_2: "BF", iso3166_3: "BFA", destatisBevCode: Integer.parseInt("258")))
    nations.add(new Nation(searchTerm: "Burundi", officialTermShort: "Burundi", officialTermLong: "die Republik Burundi", citizenship: "burundisch", continent: Continent.AFR, iso3166_2: "BI", iso3166_3: "BDI", destatisBevCode: Integer.parseInt("291")))
    nations.add(new Nation(searchTerm: "Cabo Verde", officialTermShort: "Cabo Verde", officialTermLong: "die Republik Cabo Verde", citizenship: "cabo-verdisch", continent: Continent.AFR, iso3166_2: "CV", iso3166_3: "CPV", destatisBevCode: Integer.parseInt("242")))
    nations.add(new Nation(searchTerm: "Chile", officialTermShort: "Chile", officialTermLong: "die Republik Chile", citizenship: "chilenisch", continent: Continent.AME, iso3166_2: "CL", iso3166_3: "CHL", destatisBevCode: Integer.parseInt("332")))
    nations.add(new Nation(searchTerm: "China", officialTermShort: "China", officialTermLong: "die Volksrepublik China", citizenship: "chinesisch", continent: Continent.ASI, iso3166_2: "CN", iso3166_3: "CHN", destatisBevCode: Integer.parseInt("479")))
    nations.add(new Nation(searchTerm: "Cookinseln", officialTermShort: "Cookinseln", officialTermLong: "die Cookinseln", citizenship: "neuseeländisch", continent: Continent.AOA, iso3166_2: "CK", iso3166_3: "COK", destatisBevCode: Integer.parseInt("527")))
    nations.add(new Nation(searchTerm: "Costa Rica", officialTermShort: "Costa Rica", officialTermLong: "die Republik Costa Rica", citizenship: "costa-ricanisch", continent: Continent.AME, iso3166_2: "CR", iso3166_3: "CRI", destatisBevCode: Integer.parseInt("334")))
    nations.add(new Nation(searchTerm: "Côte d’Ivoire", officialTermShort: "Côte d’Ivoire", officialTermLong: "die Republik Côte d’Ivoire", citizenship: "ivorisch", continent: Continent.AFR, iso3166_2: "CI", iso3166_3: "CIV", destatisBevCode: Integer.parseInt("231")))
    nations.add(new Nation(searchTerm: "Dänemark", officialTermShort: "Dänemark", officialTermLong: "das Königreich Dänemark", citizenship: "dänisch", continent: Continent.EUR, iso3166_2: "DK", iso3166_3: "DNK", destatisBevCode: Integer.parseInt("126")))
    nations.add(new Nation(searchTerm: "Deutschland", officialTermShort: "Deutschland", officialTermLong: "die Bundesrepublik Deutschland", citizenship: "deutsch", continent: Continent.EUR, iso3166_2: "DE", iso3166_3: "DEU", destatisBevCode: Integer.parseInt("000")))
    nations.add(new Nation(searchTerm: "Dominica", officialTermShort: "Dominica", officialTermLong: "das Commonwealth Dominica", citizenship: "dominicanisch", continent: Continent.AME, iso3166_2: "DM", iso3166_3: "DMA", destatisBevCode: Integer.parseInt("333")))
    nations.add(new Nation(searchTerm: "Dominikanische Republik", officialTermShort: "Dominikanische Republik", officialTermLong: "die Dominikanische Republik", citizenship: "dominikanisch", continent: Continent.AME, iso3166_2: "DO", iso3166_3: "DOM", destatisBevCode: Integer.parseInt("335")))
    nations.add(new Nation(searchTerm: "Dschibuti", officialTermShort: "Dschibuti", officialTermLong: "die Republik Dschibuti", citizenship: "dschibutisch", continent: Continent.AFR, iso3166_2: "DJ", iso3166_3: "DJI", destatisBevCode: Integer.parseInt("230")))
    nations.add(new Nation(searchTerm: "Ecuador", officialTermShort: "Ecuador", officialTermLong: "die Republik Ecuador", citizenship: "ecuadorianisch", continent: Continent.AME, iso3166_2: "EC", iso3166_3: "ECU", destatisBevCode: Integer.parseInt("336")))
    nations.add(new Nation(searchTerm: "El Salvador", officialTermShort: "El Salvador", officialTermLong: "die Republik El Salvador", citizenship: "salvadorianisch", continent: Continent.AME, iso3166_2: "SV", iso3166_3: "SLV", destatisBevCode: Integer.parseInt("337")))
    nations.add(new Nation(searchTerm: "Eritrea", officialTermShort: "Eritrea", officialTermLong: "der Staat Eritrea", citizenship: "eritreisch", continent: Continent.AFR, iso3166_2: "ER", iso3166_3: "ERI", destatisBevCode: Integer.parseInt("224")))
    nations.add(new Nation(searchTerm: "Estland", officialTermShort: "Estland", officialTermLong: "die Republik Estland", citizenship: "estnisch", continent: Continent.EUR, iso3166_2: "EE", iso3166_3: "EST", destatisBevCode: Integer.parseInt("127")))
    nations.add(new Nation(searchTerm: "Eswatini", officialTermShort: "Eswatini", officialTermLong: "das Königreich Eswatini", citizenship: "eswatinisch", continent: Continent.AFR, iso3166_2: "SZ", iso3166_3: "SWZ", destatisBevCode: Integer.parseInt("281")))
    nations.add(new Nation(searchTerm: "Fidschi", officialTermShort: "Fidschi", officialTermLong: "die Republik Fidschi", citizenship: "fidschianisch", continent: Continent.AOA, iso3166_2: "FJ", iso3166_3: "FJI", destatisBevCode: Integer.parseInt("526")))
    nations.add(new Nation(searchTerm: "Finnland", officialTermShort: "Finnland", officialTermLong: "die Republik Finnland", citizenship: "finnisch", continent: Continent.EUR, iso3166_2: "FI", iso3166_3: "FIN", destatisBevCode: Integer.parseInt("128")))
    nations.add(new Nation(searchTerm: "Frankreich", officialTermShort: "Frankreich", officialTermLong: "die Französische Republik", citizenship: "französisch", continent: Continent.EUR, iso3166_2: "FR", iso3166_3: "FRA", destatisBevCode: Integer.parseInt("129")))
    nations.add(new Nation(searchTerm: "Gabun", officialTermShort: "Gabun", officialTermLong: "die Gabunische Republik", citizenship: "gabunisch", continent: Continent.AFR, iso3166_2: "GA", iso3166_3: "GAB", destatisBevCode: Integer.parseInt("236")))
    nations.add(new Nation(searchTerm: "Gambia", officialTermShort: "Gambia", officialTermLong: "die Republik Gambia", citizenship: "gambisch", continent: Continent.AFR, iso3166_2: "GM", iso3166_3: "GMB", destatisBevCode: Integer.parseInt("237")))
    nations.add(new Nation(searchTerm: "Georgien", officialTermShort: "Georgien", officialTermLong: "Georgien", citizenship: "georgisch", continent: Continent.ASI, iso3166_2: "GE", iso3166_3: "GEO", destatisBevCode: Integer.parseInt("430")))
    nations.add(new Nation(searchTerm: "Ghana", officialTermShort: "Ghana", officialTermLong: "die Republik Ghana", citizenship: "ghanaisch", continent: Continent.AFR, iso3166_2: "GH", iso3166_3: "GHA", destatisBevCode: Integer.parseInt("238")))
    nations.add(new Nation(searchTerm: "Grenada", officialTermShort: "Grenada", officialTermLong: "Grenada", citizenship: "grenadisch", continent: Continent.AME, iso3166_2: "GD", iso3166_3: "GRD", destatisBevCode: Integer.parseInt("340")))
    nations.add(new Nation(searchTerm: "Griechenland", officialTermShort: "Griechenland", officialTermLong: "die Hellenische Republik", citizenship: "griechisch", continent: Continent.EUR, iso3166_2: "GR", iso3166_3: "GRC", destatisBevCode: Integer.parseInt("134")))
    nations.add(new Nation(searchTerm: "Guatemala", officialTermShort: "Guatemala", officialTermLong: "die Republik Guatemala", citizenship: "guatemaltekisch", continent: Continent.AME, iso3166_2: "GT", iso3166_3: "GTM", destatisBevCode: Integer.parseInt("345")))
    nations.add(new Nation(searchTerm: "Guinea", officialTermShort: "Guinea", officialTermLong: "die Republik Guinea", citizenship: "guineisch", continent: Continent.AFR, iso3166_2: "GN", iso3166_3: "GIN", destatisBevCode: Integer.parseInt("261")))
    nations.add(new Nation(searchTerm: "Guinea-Bissau", officialTermShort: "Guinea-Bissau", officialTermLong: "die Republik Guinea-Bissau", citizenship: "guinea-bissauisch", continent: Continent.AFR, iso3166_2: "GW", iso3166_3: "GNB", destatisBevCode: Integer.parseInt("259")))
    nations.add(new Nation(searchTerm: "Guyana", officialTermShort: "Guyana", officialTermLong: "die Kooperative Republik Guyana", citizenship: "guyanisch", continent: Continent.AME, iso3166_2: "GY", iso3166_3: "GUY", destatisBevCode: Integer.parseInt("328")))
    nations.add(new Nation(searchTerm: "Haiti", officialTermShort: "Haiti", officialTermLong: "die Republik Haiti", citizenship: "haitianisch", continent: Continent.AME, iso3166_2: "HT", iso3166_3: "HTI", destatisBevCode: Integer.parseInt("346")))
    nations.add(new Nation(searchTerm: "Honduras", officialTermShort: "Honduras", officialTermLong: "die Republik Honduras", citizenship: "honduranisch", continent: Continent.AME, iso3166_2: "HN", iso3166_3: "HND", destatisBevCode: Integer.parseInt("347")))
    nations.add(new Nation(searchTerm: "Indien", officialTermShort: "Indien", officialTermLong: "die Republik Indien", citizenship: "indisch", continent: Continent.ASI, iso3166_2: "IN", iso3166_3: "IND", destatisBevCode: Integer.parseInt("436")))
    nations.add(new Nation(searchTerm: "Indonesien", officialTermShort: "Indonesien", officialTermLong: "die Republik Indonesien", citizenship: "indonesisch", continent: Continent.ASI, iso3166_2: "ID", iso3166_3: "IDN", destatisBevCode: Integer.parseInt("437")))
    nations.add(new Nation(searchTerm: "Irak", officialTermShort: "Irak", officialTermLong: "die Republik Irak", citizenship: "irakisch", continent: Continent.ASI, iso3166_2: "IQ", iso3166_3: "IRQ", destatisBevCode: Integer.parseInt("438")))
    nations.add(new Nation(searchTerm: "Islamische Republik Iran", officialTermShort: "Islamische Republik Iran", officialTermLong: "die Islamische Republik Iran", citizenship: "iranisch", continent: Continent.ASI, iso3166_2: "IR", iso3166_3: "IRN", destatisBevCode: Integer.parseInt("439")))
    nations.add(new Nation(searchTerm: "Irland", officialTermShort: "Irland", officialTermLong: "Irland", citizenship: "irisch", continent: Continent.EUR, iso3166_2: "IE", iso3166_3: "IRL", destatisBevCode: Integer.parseInt("135")))
    nations.add(new Nation(searchTerm: "Island", officialTermShort: "Island", officialTermLong: "Island", citizenship: "isländisch", continent: Continent.EUR, iso3166_2: "IS", iso3166_3: "ISL", destatisBevCode: Integer.parseInt("136")))
    nations.add(new Nation(searchTerm: "Israel", officialTermShort: "Israel", officialTermLong: "der Staat Israel", citizenship: "israelisch", continent: Continent.ASI, iso3166_2: "IL", iso3166_3: "ISR", destatisBevCode: Integer.parseInt("441")))
    nations.add(new Nation(searchTerm: "Italien", officialTermShort: "Italien", officialTermLong: "die Italienische Republik", citizenship: "italienisch", continent: Continent.EUR, iso3166_2: "IT", iso3166_3: "ITA", destatisBevCode: Integer.parseInt("137")))
    nations.add(new Nation(searchTerm: "Jamaika", officialTermShort: "Jamaika", officialTermLong: "Jamaika", citizenship: "jamaikanisch", continent: Continent.AME, iso3166_2: "JM", iso3166_3: "JAM", destatisBevCode: Integer.parseInt("355")))
    nations.add(new Nation(searchTerm: "Japan", officialTermShort: "Japan", officialTermLong: "Japan", citizenship: "japanisch", continent: Continent.ASI, iso3166_2: "JP", iso3166_3: "JPN", destatisBevCode: Integer.parseInt("442")))
    nations.add(new Nation(searchTerm: "Jemen", officialTermShort: "Jemen", officialTermLong: "die Republik Jemen", citizenship: "jemenitisch", continent: Continent.ASI, iso3166_2: "YE", iso3166_3: "YEM", destatisBevCode: Integer.parseInt("421")))
    nations.add(new Nation(searchTerm: "Jordanien", officialTermShort: "Jordanien", officialTermLong: "das Haschemitische Königreich Jordanien", citizenship: "jordanisch", continent: Continent.ASI, iso3166_2: "JO", iso3166_3: "JOR", destatisBevCode: Integer.parseInt("445")))
    nations.add(new Nation(searchTerm: "Kambodscha", officialTermShort: "Kambodscha", officialTermLong: "das Königreich Kambodscha", citizenship: "kambodschanisch", continent: Continent.ASI, iso3166_2: "KH", iso3166_3: "KHM", destatisBevCode: Integer.parseInt("446")))
    nations.add(new Nation(searchTerm: "Kamerun", officialTermShort: "Kamerun", officialTermLong: "die Republik Kamerun", citizenship: "kamerunisch", continent: Continent.AFR, iso3166_2: "CM", iso3166_3: "CMR", destatisBevCode: Integer.parseInt("262")))
    nations.add(new Nation(searchTerm: "Kanada", officialTermShort: "Kanada", officialTermLong: "Kanada", citizenship: "kanadisch", continent: Continent.AME, iso3166_2: "CA", iso3166_3: "CAN", destatisBevCode: Integer.parseInt("348")))
    nations.add(new Nation(searchTerm: "Kasachstan", officialTermShort: "Kasachstan", officialTermLong: "die Republik Kasachstan", citizenship: "kasachisch", continent: Continent.ASI, iso3166_2: "KZ", iso3166_3: "KAZ", destatisBevCode: Integer.parseInt("444")))
    nations.add(new Nation(searchTerm: "Katar", officialTermShort: "Katar", officialTermLong: "der Staat Katar", citizenship: "katarisch", continent: Continent.ASI, iso3166_2: "QA", iso3166_3: "QAT", destatisBevCode: Integer.parseInt("447")))
    nations.add(new Nation(searchTerm: "Kenia", officialTermShort: "Kenia", officialTermLong: "die Republik Kenia", citizenship: "kenianisch", continent: Continent.AFR, iso3166_2: "KE", iso3166_3: "KEN", destatisBevCode: Integer.parseInt("243")))
    nations.add(new Nation(searchTerm: "Kirgisistan", officialTermShort: "Kirgisistan", officialTermLong: "die Kirgisische Republik", citizenship: "kirgisisch", continent: Continent.ASI, iso3166_2: "KG", iso3166_3: "KGZ", destatisBevCode: Integer.parseInt("450")))
    nations.add(new Nation(searchTerm: "Kiribati", officialTermShort: "Kiribati", officialTermLong: "die Republik Kiribati", citizenship: "kiribatisch", continent: Continent.AOA, iso3166_2: "KI", iso3166_3: "KIR", destatisBevCode: Integer.parseInt("530")))
    nations.add(new Nation(searchTerm: "Kolumbien", officialTermShort: "Kolumbien", officialTermLong: "die Republik Kolumbien", citizenship: "kolumbianisch", continent: Continent.AME, iso3166_2: "CO", iso3166_3: "COL", destatisBevCode: Integer.parseInt("349")))
    nations.add(new Nation(searchTerm: "Komoren", officialTermShort: "Komoren", officialTermLong: "die Union der Komoren", citizenship: "komorisch", continent: Continent.AFR, iso3166_2: "KM", iso3166_3: "COM", destatisBevCode: Integer.parseInt("244")))
    nations.add(new Nation(searchTerm: "Kongo", officialTermShort: "Kongo", officialTermLong: "die Republik Kongo", citizenship: "kongolesisch", continent: Continent.AFR, iso3166_2: "CG", iso3166_3: "COG", destatisBevCode: Integer.parseInt("245")))
    nations.add(new Nation(searchTerm: "Demokratische Republik Kongo", officialTermShort: "Demokratische Republik Kongo", officialTermLong: "die Demokratische Republik Kongo", citizenship: "der Demokratischen Republik Kongo", continent: Continent.AFR, iso3166_2: "CD", iso3166_3: "COD", destatisBevCode: Integer.parseInt("246")))
    nations.add(new Nation(searchTerm: "Demokratische Volksrepublik Korea", officialTermShort: "Demokratische Volksrepublik Korea", officialTermLong: "die Demokratische Volksrepublik Korea", citizenship: "der Demokratischen Volksrepublik Korea", continent: Continent.ASI, iso3166_2: "KP", iso3166_3: "PRK", destatisBevCode: Integer.parseInt("434")))
    nations.add(new Nation(searchTerm: "Republik Korea", officialTermShort: "Republik Korea", officialTermLong: "die Republik Korea", citizenship: "der Republik Korea", continent: Continent.ASI, iso3166_2: "KR", iso3166_3: "KOR", destatisBevCode: Integer.parseInt("467")))
    nations.add(new Nation(searchTerm: "Kosovo", officialTermShort: "Kosovo", officialTermLong: "die Republik Kosovo", citizenship: "kosovarisch", continent: Continent.EUR, iso3166_2: "XK", iso3166_3: "XXK", destatisBevCode: Integer.parseInt("150")))
    nations.add(new Nation(searchTerm: "Kroatien", officialTermShort: "Kroatien", officialTermLong: "die Republik Kroatien", citizenship: "kroatisch", continent: Continent.EUR, iso3166_2: "HR", iso3166_3: "HRV", destatisBevCode: Integer.parseInt("130")))
    nations.add(new Nation(searchTerm: "Kuba", officialTermShort: "Kuba", officialTermLong: "die Republik Kuba", citizenship: "kubanisch", continent: Continent.AME, iso3166_2: "CU", iso3166_3: "CUB", destatisBevCode: Integer.parseInt("351")))
    nations.add(new Nation(searchTerm: "Kuwait", officialTermShort: "Kuwait", officialTermLong: "der Staat Kuwait", citizenship: "kuwaitisch", continent: Continent.ASI, iso3166_2: "KW", iso3166_3: "KWT", destatisBevCode: Integer.parseInt("448")))
    nations.add(new Nation(searchTerm: "Demokratische Volksrepublik Laos", officialTermShort: "Demokratische Volksrepublik Laos", officialTermLong: "die Demokratische Volksrepublik Laos", citizenship: "laotisch", continent: Continent.ASI, iso3166_2: "LA", iso3166_3: "LAO", destatisBevCode: Integer.parseInt("449")))
    nations.add(new Nation(searchTerm: "Lesotho", officialTermShort: "Lesotho", officialTermLong: "das Königreich Lesotho", citizenship: "lesothisch", continent: Continent.AFR, iso3166_2: "LS", iso3166_3: "LSO", destatisBevCode: Integer.parseInt("226")))
    nations.add(new Nation(searchTerm: "Lettland", officialTermShort: "Lettland", officialTermLong: "die Republik Lettland", citizenship: "lettisch", continent: Continent.EUR, iso3166_2: "LV", iso3166_3: "LVA", destatisBevCode: Integer.parseInt("139")))
    nations.add(new Nation(searchTerm: "Libanon", officialTermShort: "Libanon", officialTermLong: "die Libanesische Republik", citizenship: "libanesisch", continent: Continent.ASI, iso3166_2: "LB", iso3166_3: "LBN", destatisBevCode: Integer.parseInt("451")))
    nations.add(new Nation(searchTerm: "Liberia", officialTermShort: "Liberia", officialTermLong: "die Republik Liberia", citizenship: "liberianisch", continent: Continent.AFR, iso3166_2: "LR", iso3166_3: "LBR", destatisBevCode: Integer.parseInt("247")))
    nations.add(new Nation(searchTerm: "Libyen", officialTermShort: "Libyen", officialTermLong: "der Staat Libyen", citizenship: "libysch", continent: Continent.AFR, iso3166_2: "LY", iso3166_3: "LBY", destatisBevCode: Integer.parseInt("248")))
    nations.add(new Nation(searchTerm: "Liechtenstein", officialTermShort: "Liechtenstein", officialTermLong: "das Fürstentum Liechtenstein", citizenship: "liechtensteinisch", continent: Continent.EUR, iso3166_2: "LI", iso3166_3: "LIE", destatisBevCode: Integer.parseInt("141")))
    nations.add(new Nation(searchTerm: "Litauen", officialTermShort: "Litauen", officialTermLong: "die Republik Litauen", citizenship: "litauisch", continent: Continent.EUR, iso3166_2: "LT", iso3166_3: "LTU", destatisBevCode: Integer.parseInt("142")))
    nations.add(new Nation(searchTerm: "Luxemburg", officialTermShort: "Luxemburg", officialTermLong: "das Großherzogtum Luxemburg", citizenship: "luxemburgisch", continent: Continent.EUR, iso3166_2: "LU", iso3166_3: "LUX", destatisBevCode: Integer.parseInt("143")))
    nations.add(new Nation(searchTerm: "Madagaskar", officialTermShort: "Madagaskar", officialTermLong: "die Republik Madagaskar", citizenship: "madagassisch", continent: Continent.AFR, iso3166_2: "MG", iso3166_3: "MDG", destatisBevCode: Integer.parseInt("249")))
    nations.add(new Nation(searchTerm: "Malawi", officialTermShort: "Malawi", officialTermLong: "die Republik Malawi", citizenship: "malawisch", continent: Continent.AFR, iso3166_2: "MW", iso3166_3: "MWI", destatisBevCode: Integer.parseInt("256")))
    nations.add(new Nation(searchTerm: "Malaysia", officialTermShort: "Malaysia", officialTermLong: "Malaysia", citizenship: "malaysisch", continent: Continent.ASI, iso3166_2: "MY", iso3166_3: "MYS", destatisBevCode: Integer.parseInt("482")))
    nations.add(new Nation(searchTerm: "Malediven", officialTermShort: "Malediven", officialTermLong: "die Republik Malediven", citizenship: "maledivisch", continent: Continent.ASI, iso3166_2: "MV", iso3166_3: "MDV", destatisBevCode: Integer.parseInt("454")))
    nations.add(new Nation(searchTerm: "Mali", officialTermShort: "Mali", officialTermLong: "die Republik Mali", citizenship: "malisch", continent: Continent.AFR, iso3166_2: "ML", iso3166_3: "MLI", destatisBevCode: Integer.parseInt("251")))
    nations.add(new Nation(searchTerm: "Malta", officialTermShort: "Malta", officialTermLong: "die Republik Malta", citizenship: "maltesisch", continent: Continent.EUR, iso3166_2: "MT", iso3166_3: "MLT", destatisBevCode: Integer.parseInt("145")))
    nations.add(new Nation(searchTerm: "Marokko", officialTermShort: "Marokko", officialTermLong: "das Königreich Marokko", citizenship: "marokkanisch", continent: Continent.AFR, iso3166_2: "MA", iso3166_3: "MAR", destatisBevCode: Integer.parseInt("252")))
    nations.add(new Nation(searchTerm: "Marshallinseln", officialTermShort: "Marshallinseln", officialTermLong: "die Republik Marshallinseln", citizenship: "marshallisch", continent: Continent.AOA, iso3166_2: "MH", iso3166_3: "MHL", destatisBevCode: Integer.parseInt("544")))
    nations.add(new Nation(searchTerm: "Mauretanien", officialTermShort: "Mauretanien", officialTermLong: "die Islamische Republik Mauretanien", citizenship: "mauretanisch", continent: Continent.AFR, iso3166_2: "MR", iso3166_3: "MRT", destatisBevCode: Integer.parseInt("239")))
    nations.add(new Nation(searchTerm: "Mauritius", officialTermShort: "Mauritius", officialTermLong: "die Republik Mauritius", citizenship: "mauritisch", continent: Continent.AFR, iso3166_2: "MU", iso3166_3: "MUS", destatisBevCode: Integer.parseInt("253")))
    nations.add(new Nation(searchTerm: "Mexiko", officialTermShort: "Mexiko", officialTermLong: "die Vereinigten Mexikanischen Staaten", citizenship: "mexikanisch", continent: Continent.AME, iso3166_2: "MX", iso3166_3: "MEX", destatisBevCode: Integer.parseInt("353")))
    nations.add(new Nation(searchTerm: "Föderierte Staaten von Mikronesien", officialTermShort: "Föderierte Staaten von Mikronesien", officialTermLong: "die Föderierten Staaten von Mikronesien", citizenship: "mikronesisch", continent: Continent.AOA, iso3166_2: "FM", iso3166_3: "FSM", destatisBevCode: Integer.parseInt("545")))
    nations.add(new Nation(searchTerm: "Republik Moldau", officialTermShort: "Republik Moldau", officialTermLong: "die Republik Moldau", citizenship: "moldauisch", continent: Continent.EUR, iso3166_2: "MD", iso3166_3: "MDA", destatisBevCode: Integer.parseInt("146")))
    nations.add(new Nation(searchTerm: "Monaco", officialTermShort: "Monaco", officialTermLong: "das Fürstentum Monaco", citizenship: "monegassisch", continent: Continent.EUR, iso3166_2: "MC", iso3166_3: "MCO", destatisBevCode: Integer.parseInt("147")))
    nations.add(new Nation(searchTerm: "Mongolei", officialTermShort: "Mongolei", officialTermLong: "die Mongolei", citizenship: "mongolisch", continent: Continent.ASI, iso3166_2: "MN", iso3166_3: "MNG", destatisBevCode: Integer.parseInt("457")))
    nations.add(new Nation(searchTerm: "Montenegro", officialTermShort: "Montenegro", officialTermLong: "Montenegro", citizenship: "montenegrinisch", continent: Continent.EUR, iso3166_2: "ME", iso3166_3: "MNE", destatisBevCode: Integer.parseInt("140")))
    nations.add(new Nation(searchTerm: "Mosambik", officialTermShort: "Mosambik", officialTermLong: "die Republik Mosambik", citizenship: "mosambikanisch", continent: Continent.AFR, iso3166_2: "MZ", iso3166_3: "MOZ", destatisBevCode: Integer.parseInt("254")))
    nations.add(new Nation(searchTerm: "Myanmar", officialTermShort: "Myanmar", officialTermLong: "die Republik der Union Myanmar", citizenship: "myanmarisch", continent: Continent.ASI, iso3166_2: "MM", iso3166_3: "MMR", destatisBevCode: Integer.parseInt("427")))
    nations.add(new Nation(searchTerm: "Namibia", officialTermShort: "Namibia", officialTermLong: "die Republik Namibia", citizenship: "namibisch", continent: Continent.AFR, iso3166_2: "NA", iso3166_3: "NAM", destatisBevCode: Integer.parseInt("267")))
    nations.add(new Nation(searchTerm: "Nauru", officialTermShort: "Nauru", officialTermLong: "die Republik Nauru", citizenship: "nauruisch", continent: Continent.AOA, iso3166_2: "NR", iso3166_3: "NRU", destatisBevCode: Integer.parseInt("531")))
    nations.add(new Nation(searchTerm: "Nepal", officialTermShort: "Nepal", officialTermLong: "Nepal", citizenship: "nepalesisch", continent: Continent.ASI, iso3166_2: "NP", iso3166_3: "NPL", destatisBevCode: Integer.parseInt("458")))
    nations.add(new Nation(searchTerm: "Neuseeland", officialTermShort: "Neuseeland", officialTermLong: "Neuseeland", citizenship: "neuseeländisch", continent: Continent.AOA, iso3166_2: "NZ", iso3166_3: "NZL", destatisBevCode: Integer.parseInt("536")))
    nations.add(new Nation(searchTerm: "Nicaragua", officialTermShort: "Nicaragua", officialTermLong: "die Republik Nicaragua", citizenship: "nicaraguanisch", continent: Continent.AME, iso3166_2: "NI", iso3166_3: "NIC", destatisBevCode: Integer.parseInt("354")))
    nations.add(new Nation(searchTerm: "Niederlande", officialTermShort: "Niederlande", officialTermLong: "das Königreich der Niederlande", citizenship: "niederländisch", continent: Continent.EUR, iso3166_2: "NL", iso3166_3: "NLD", destatisBevCode: Integer.parseInt("148")))
    nations.add(new Nation(searchTerm: "Niger", officialTermShort: "Niger", officialTermLong: "die Republik Niger", citizenship: "nigrisch", continent: Continent.AFR, iso3166_2: "NE", iso3166_3: "NER", destatisBevCode: Integer.parseInt("255")))
    nations.add(new Nation(searchTerm: "Nigeria", officialTermShort: "Nigeria", officialTermLong: "die Bundesrepublik Nigeria", citizenship: "nigerianisch", continent: Continent.AFR, iso3166_2: "NG", iso3166_3: "NGA", destatisBevCode: Integer.parseInt("232")))
    nations.add(new Nation(searchTerm: "Niue", officialTermShort: "Niue", officialTermLong: "Niue", citizenship: "neuseeländisch", continent: Continent.AOA, iso3166_2: "NU", iso3166_3: "NIU", destatisBevCode: Integer.parseInt("533")))
    nations.add(new Nation(searchTerm: "Nordmazedonien", officialTermShort: "Nordmazedonien", officialTermLong: "die Republik Nordmazedonien", citizenship: "mazedonisch/Bürger der Republik Nordmazedonien", continent: Continent.EUR, iso3166_2: "MK", iso3166_3: "MKD", destatisBevCode: Integer.parseInt("144")))
    nations.add(new Nation(searchTerm: "Norwegen", officialTermShort: "Norwegen", officialTermLong: "das Königreich Norwegen", citizenship: "norwegisch", continent: Continent.EUR, iso3166_2: "NO", iso3166_3: "NOR", destatisBevCode: Integer.parseInt("149")))
    nations.add(new Nation(searchTerm: "Oman", officialTermShort: "Oman", officialTermLong: "das Sultanat Oman", citizenship: "omanisch", continent: Continent.ASI, iso3166_2: "OM", iso3166_3: "OMN", destatisBevCode: Integer.parseInt("456")))
    nations.add(new Nation(searchTerm: "Österreich", officialTermShort: "Österreich", officialTermLong: "die Republik Österreich", citizenship: "österreichisch", continent: Continent.EUR, iso3166_2: "AT", iso3166_3: "AUT", destatisBevCode: Integer.parseInt("151")))
    nations.add(new Nation(searchTerm: "Pakistan", officialTermShort: "Pakistan", officialTermLong: "die Islamische Republik Pakistan", citizenship: "pakistanisch", continent: Continent.ASI, iso3166_2: "PK", iso3166_3: "PAK", destatisBevCode: Integer.parseInt("461")))
    nations.add(new Nation(searchTerm: "Palau", officialTermShort: "Palau", officialTermLong: "die Republik Palau", citizenship: "palauisch", continent: Continent.AOA, iso3166_2: "PW", iso3166_3: "PLW", destatisBevCode: Integer.parseInt("537")))
    nations.add(new Nation(searchTerm: "Panama", officialTermShort: "Panama", officialTermLong: "die Republik Panama", citizenship: "panamaisch", continent: Continent.AME, iso3166_2: "PA", iso3166_3: "PAN", destatisBevCode: Integer.parseInt("357")))
    nations.add(new Nation(searchTerm: "Papua-Neuguinea", officialTermShort: "Papua-Neuguinea", officialTermLong: "der Unabhängige Staat Papua-Neuguinea", citizenship: "papua-neuguineisch", continent: Continent.AOA, iso3166_2: "PG", iso3166_3: "PNG", destatisBevCode: Integer.parseInt("538")))
    nations.add(new Nation(searchTerm: "Paraguay", officialTermShort: "Paraguay", officialTermLong: "die Republik Paraguay", citizenship: "paraguayisch", continent: Continent.AME, iso3166_2: "PY", iso3166_3: "PRY", destatisBevCode: Integer.parseInt("359")))
    nations.add(new Nation(searchTerm: "Peru", officialTermShort: "Peru", officialTermLong: "die Republik Peru", citizenship: "peruanisch", continent: Continent.AME, iso3166_2: "PE", iso3166_3: "PER", destatisBevCode: Integer.parseInt("361")))
    nations.add(new Nation(searchTerm: "Philippinen", officialTermShort: "Philippinen", officialTermLong: "die Republik der Philippinen", citizenship: "philippinisch", continent: Continent.ASI, iso3166_2: "PH", iso3166_3: "PHL", destatisBevCode: Integer.parseInt("462")))
    nations.add(new Nation(searchTerm: "Polen", officialTermShort: "Polen", officialTermLong: "die Republik Polen", citizenship: "polnisch", continent: Continent.EUR, iso3166_2: "PL", iso3166_3: "POL", destatisBevCode: Integer.parseInt("152")))
    nations.add(new Nation(searchTerm: "Portugal", officialTermShort: "Portugal", officialTermLong: "die Portugiesische Republik", citizenship: "portugiesisch", continent: Continent.EUR, iso3166_2: "PT", iso3166_3: "PRT", destatisBevCode: Integer.parseInt("153")))
    nations.add(new Nation(searchTerm: "Ruanda", officialTermShort: "Ruanda", officialTermLong: "die Republik Ruanda", citizenship: "ruandisch", continent: Continent.AFR, iso3166_2: "RW", iso3166_3: "RWA", destatisBevCode: Integer.parseInt("265")))
    nations.add(new Nation(searchTerm: "Rumänien", officialTermShort: "Rumänien", officialTermLong: "Rumänien", citizenship: "rumänisch", continent: Continent.EUR, iso3166_2: "RO", iso3166_3: "ROU", destatisBevCode: Integer.parseInt("154")))
    nations.add(new Nation(searchTerm: "Russische Föderation", officialTermShort: "Russische Föderation", officialTermLong: "die Russische Föderation", citizenship: "russisch", continent: Continent.EUR, iso3166_2: "RU", iso3166_3: "RUS", destatisBevCode: Integer.parseInt("160")))
    nations.add(new Nation(searchTerm: "Salomonen", officialTermShort: "Salomonen", officialTermLong: "die Salomonen", citizenship: "salomonisch", continent: Continent.AOA, iso3166_2: "SB", iso3166_3: "SLB", destatisBevCode: Integer.parseInt("524")))
    nations.add(new Nation(searchTerm: "Sambia", officialTermShort: "Sambia", officialTermLong: "die Republik Sambia", citizenship: "sambisch", continent: Continent.AFR, iso3166_2: "ZM", iso3166_3: "ZMB", destatisBevCode: Integer.parseInt("257")))
    nations.add(new Nation(searchTerm: "Samoa", officialTermShort: "Samoa", officialTermLong: "der Unabhängige Staat Samoa", citizenship: "samoanisch", continent: Continent.AOA, iso3166_2: "WS", iso3166_3: "WSM", destatisBevCode: Integer.parseInt("543")))
    nations.add(new Nation(searchTerm: "San Marino", officialTermShort: "San Marino", officialTermLong: "die Republik San Marino", citizenship: "san-marinesisch", continent: Continent.EUR, iso3166_2: "SM", iso3166_3: "SMR", destatisBevCode: Integer.parseInt("156")))
    nations.add(new Nation(searchTerm: "São Tomé und Príncipe", officialTermShort: "São Tomé und Príncipe", officialTermLong: "die Demokratische Republik São Tomé und Príncipe", citizenship: "são-toméisch", continent: Continent.AFR, iso3166_2: "ST", iso3166_3: "STP", destatisBevCode: Integer.parseInt("268")))
    nations.add(new Nation(searchTerm: "Saudi-Arabien", officialTermShort: "Saudi-Arabien", officialTermLong: "das Königreich Saudi-Arabien", citizenship: "saudi-arabisch", continent: Continent.ASI, iso3166_2: "SA", iso3166_3: "SAU", destatisBevCode: Integer.parseInt("472")))
    nations.add(new Nation(searchTerm: "Schweden", officialTermShort: "Schweden", officialTermLong: "das Königreich Schweden", citizenship: "schwedisch", continent: Continent.EUR, iso3166_2: "SE", iso3166_3: "SWE", destatisBevCode: Integer.parseInt("157")))
    nations.add(new Nation(searchTerm: "Schweiz", officialTermShort: "Schweiz", officialTermLong: "die Schweizerische Eidgenossenschaft", citizenship: "schweizerisch", continent: Continent.EUR, iso3166_2: "CH", iso3166_3: "CHE", destatisBevCode: Integer.parseInt("158")))
    nations.add(new Nation(searchTerm: "Senegal", officialTermShort: "Senegal", officialTermLong: "die Republik Senegal", citizenship: "senegalesisch", continent: Continent.AFR, iso3166_2: "SN", iso3166_3: "SEN", destatisBevCode: Integer.parseInt("269")))
    nations.add(new Nation(searchTerm: "Serbien", officialTermShort: "Serbien", officialTermLong: "die Republik Serbien", citizenship: "serbisch", continent: Continent.EUR, iso3166_2: "RS", iso3166_3: "SRB", destatisBevCode: Integer.parseInt("170")))
    nations.add(new Nation(searchTerm: "Seychellen", officialTermShort: "Seychellen", officialTermLong: "die Republik Seychellen", citizenship: "seychellisch", continent: Continent.AFR, iso3166_2: "SC", iso3166_3: "SYC", destatisBevCode: Integer.parseInt("271")))
    nations.add(new Nation(searchTerm: "Sierra Leone", officialTermShort: "Sierra Leone", officialTermLong: "die Republik Sierra Leone", citizenship: "sierra-leonisch", continent: Continent.AFR, iso3166_2: "SL", iso3166_3: "SLE", destatisBevCode: Integer.parseInt("272")))
    nations.add(new Nation(searchTerm: "Simbabwe", officialTermShort: "Simbabwe", officialTermLong: "die Republik Simbabwe", citizenship: "simbabwisch", continent: Continent.AFR, iso3166_2: "ZW", iso3166_3: "ZWE", destatisBevCode: Integer.parseInt("233")))
    nations.add(new Nation(searchTerm: "Singapur", officialTermShort: "Singapur", officialTermLong: "die Republik Singapur", citizenship: "singapurisch", continent: Continent.ASI, iso3166_2: "SG", iso3166_3: "SGP", destatisBevCode: Integer.parseInt("474")))
    nations.add(new Nation(searchTerm: "Slowakei", officialTermShort: "Slowakei", officialTermLong: "die Slowakische Republik", citizenship: "slowakisch", continent: Continent.EUR, iso3166_2: "SK", iso3166_3: "SVK", destatisBevCode: Integer.parseInt("155")))
    nations.add(new Nation(searchTerm: "Slowenien", officialTermShort: "Slowenien", officialTermLong: "die Republik Slowenien", citizenship: "slowenisch", continent: Continent.EUR, iso3166_2: "SI", iso3166_3: "SVN", destatisBevCode: Integer.parseInt("131")))
    nations.add(new Nation(searchTerm: "Somalia", officialTermShort: "Somalia", officialTermLong: "die Bundesrepublik Somalia", citizenship: "somalisch", continent: Continent.AFR, iso3166_2: "SO", iso3166_3: "SOM", destatisBevCode: Integer.parseInt("273")))
    nations.add(new Nation(searchTerm: "Spanien", officialTermShort: "Spanien", officialTermLong: "das Königreich Spanien", citizenship: "spanisch", continent: Continent.EUR, iso3166_2: "ES", iso3166_3: "ESP", destatisBevCode: Integer.parseInt("161")))
    nations.add(new Nation(searchTerm: "Sri Lanka", officialTermShort: "Sri Lanka", officialTermLong: "die Demokratische Sozialistische Republik Sri Lanka", citizenship: "sri-lankisch", continent: Continent.ASI, iso3166_2: "LK", iso3166_3: "LKA", destatisBevCode: Integer.parseInt("431")))
    nations.add(new Nation(searchTerm: "St. Kitts und Nevis", officialTermShort: "St. Kitts und Nevis", officialTermLong: "die Föderation St. Kitts und Nevis", citizenship: "von St. Kitts und Nevis", continent: Continent.AME, iso3166_2: "KN", iso3166_3: "KNA", destatisBevCode: Integer.parseInt("370")))
    nations.add(new Nation(searchTerm: "St. Lucia", officialTermShort: "St. Lucia", officialTermLong: "St. Lucia", citizenship: "lucianisch", continent: Continent.AME, iso3166_2: "LC", iso3166_3: "LCA", destatisBevCode: Integer.parseInt("366")))
    nations.add(new Nation(searchTerm: "St. Vincent und die Grenadinen", officialTermShort: "St. Vincent und die Grenadinen", officialTermLong: "St. Vincent und die Grenadinen", citizenship: "vincentisch", continent: Continent.AME, iso3166_2: "VC", iso3166_3: "VCT", destatisBevCode: Integer.parseInt("369")))
    nations.add(new Nation(searchTerm: "Südafrika", officialTermShort: "Südafrika", officialTermLong: "die Republik Südafrika", citizenship: "südafrikanisch", continent: Continent.AFR, iso3166_2: "ZA", iso3166_3: "ZAF", destatisBevCode: Integer.parseInt("263")))
    nations.add(new Nation(searchTerm: "Sudan", officialTermShort: "Sudan", officialTermLong: "die Republik Sudan", citizenship: "sudanesisch", continent: Continent.AFR, iso3166_2: "SD", iso3166_3: "SDN", destatisBevCode: Integer.parseInt("277")))
    nations.add(new Nation(searchTerm: "Südsudan", officialTermShort: "Südsudan", officialTermLong: "die Republik Südsudan", citizenship: "südsudanesisch", continent: Continent.AFR, iso3166_2: "SS", iso3166_3: "SSD", destatisBevCode: Integer.parseInt("278")))
    nations.add(new Nation(searchTerm: "Suriname", officialTermShort: "Suriname", officialTermLong: "die Republik Suriname", citizenship: "surinamisch", continent: Continent.AME, iso3166_2: "SR", iso3166_3: "SUR", destatisBevCode: Integer.parseInt("364")))
    nations.add(new Nation(searchTerm: "Arabische Republik Syrien", officialTermShort: "Arabische Republik Syrien", officialTermLong: "die Arabische Republik Syrien", citizenship: "syrisch", continent: Continent.ASI, iso3166_2: "SY", iso3166_3: "SYR", destatisBevCode: Integer.parseInt("475")))
    nations.add(new Nation(searchTerm: "Tadschikistan", officialTermShort: "Tadschikistan", officialTermLong: "die Republik Tadschikistan", citizenship: "tadschikisch", continent: Continent.ASI, iso3166_2: "TJ", iso3166_3: "TJK", destatisBevCode: Integer.parseInt("470")))
    nations.add(new Nation(searchTerm: "Vereinigte Republik Tansania", officialTermShort: "Vereinigte Republik Tansania", officialTermLong: "die Vereinigte Republik Tansania", citizenship: "tansanisch", continent: Continent.AFR, iso3166_2: "TZ", iso3166_3: "TZA", destatisBevCode: Integer.parseInt("282")))
    nations.add(new Nation(searchTerm: "Thailand", officialTermShort: "Thailand", officialTermLong: "das Königreich Thailand", citizenship: "thailändisch", continent: Continent.ASI, iso3166_2: "TH", iso3166_3: "THA", destatisBevCode: Integer.parseInt("476")))
    nations.add(new Nation(searchTerm: "Timor-Leste", officialTermShort: "Timor-Leste", officialTermLong: "die Demokratische Republik Timor-Leste", citizenship: "von Timor-Leste", continent: Continent.ASI, iso3166_2: "TL", iso3166_3: "TLS", destatisBevCode: Integer.parseInt("483")))
    nations.add(new Nation(searchTerm: "Togo", officialTermShort: "Togo", officialTermLong: "die Republik Togo", citizenship: "togoisch", continent: Continent.AFR, iso3166_2: "TG", iso3166_3: "TGO", destatisBevCode: Integer.parseInt("283")))
    nations.add(new Nation(searchTerm: "Tonga", officialTermShort: "Tonga", officialTermLong: "das Königreich Tonga", citizenship: "tongaisch", continent: Continent.AOA, iso3166_2: "TO", iso3166_3: "TON", destatisBevCode: Integer.parseInt("541")))
    nations.add(new Nation(searchTerm: "Trinidad und Tobago", officialTermShort: "Trinidad und Tobago", officialTermLong: "die Republik Trinidad und Tobago", citizenship: "von Trinidad und Tobago", continent: Continent.AME, iso3166_2: "TT", iso3166_3: "TTO", destatisBevCode: Integer.parseInt("371")))
    nations.add(new Nation(searchTerm: "Tschad", officialTermShort: "Tschad", officialTermLong: "die Republik Tschad", citizenship: "tschadisch", continent: Continent.AFR, iso3166_2: "TD", iso3166_3: "TCD", destatisBevCode: Integer.parseInt("284")))
    nations.add(new Nation(searchTerm: "Tschechien", officialTermShort: "Tschechien", officialTermLong: "die Tschechische Republik", citizenship: "tschechisch", continent: Continent.EUR, iso3166_2: "CZ", iso3166_3: "CZE", destatisBevCode: Integer.parseInt("164")))
    nations.add(new Nation(searchTerm: "Tunesien", officialTermShort: "Tunesien", officialTermLong: "die Tunesische Republik", citizenship: "tunesisch", continent: Continent.AFR, iso3166_2: "TN", iso3166_3: "TUN", destatisBevCode: Integer.parseInt("285")))
    nations.add(new Nation(searchTerm: "Türkei", officialTermShort: "Türkei", officialTermLong: "die Republik Türkei", citizenship: "türkisch", continent: Continent.EUR, iso3166_2: "TR", iso3166_3: "TUR", destatisBevCode: Integer.parseInt("163")))
    nations.add(new Nation(searchTerm: "Turkmenistan", officialTermShort: "Turkmenistan", officialTermLong: "Turkmenistan", citizenship: "turkmenisch", continent: Continent.ASI, iso3166_2: "TM", iso3166_3: "TKM", destatisBevCode: Integer.parseInt("471")))
    nations.add(new Nation(searchTerm: "Tuvalu", officialTermShort: "Tuvalu", officialTermLong: "Tuvalu", citizenship: "tuvaluisch", continent: Continent.AOA, iso3166_2: "TV", iso3166_3: "TUV", destatisBevCode: Integer.parseInt("540")))
    nations.add(new Nation(searchTerm: "Uganda", officialTermShort: "Uganda", officialTermLong: "die Republik Uganda", citizenship: "ugandisch", continent: Continent.AFR, iso3166_2: "UG", iso3166_3: "UGA", destatisBevCode: Integer.parseInt("286")))
    nations.add(new Nation(searchTerm: "Ukraine", officialTermShort: "Ukraine", officialTermLong: "die Ukraine", citizenship: "ukrainisch", continent: Continent.EUR, iso3166_2: "UA", iso3166_3: "UKR", destatisBevCode: Integer.parseInt("166")))
    nations.add(new Nation(searchTerm: "Ungarn", officialTermShort: "Ungarn", officialTermLong: "Ungarn", citizenship: "ungarisch", continent: Continent.EUR, iso3166_2: "HU", iso3166_3: "HUN", destatisBevCode: Integer.parseInt("165")))
    nations.add(new Nation(searchTerm: "Uruguay", officialTermShort: "Uruguay", officialTermLong: "die Republik Östlich des Uruguay", citizenship: "uruguayisch", continent: Continent.AME, iso3166_2: "UY", iso3166_3: "URY", destatisBevCode: Integer.parseInt("365")))
    nations.add(new Nation(searchTerm: "Usbekistan", officialTermShort: "Usbekistan", officialTermLong: "die Republik Usbekistan", citizenship: "usbekisch", continent: Continent.ASI, iso3166_2: "UZ", iso3166_3: "UZB", destatisBevCode: Integer.parseInt("477")))
    nations.add(new Nation(searchTerm: "Vanuatu", officialTermShort: "Vanuatu", officialTermLong: "die Republik Vanuatu", citizenship: "vanuatuisch", continent: Continent.AOA, iso3166_2: "VU", iso3166_3: "VUT", destatisBevCode: Integer.parseInt("532")))
    nations.add(new Nation(searchTerm: "Vatikanstadt", officialTermShort: "Vatikanstadt", officialTermLong: "der Staat Vatikanstadt", citizenship: "vatikanisch", continent: Continent.EUR, iso3166_2: "VA", iso3166_3: "VAT", destatisBevCode: Integer.parseInt("167")))
    nations.add(new Nation(searchTerm: "Bolivarische Republik Venezuela", officialTermShort: "Bolivarische Republik Venezuela", officialTermLong: "die Bolivarische Republik Venezuela", citizenship: "venezolanisch", continent: Continent.AME, iso3166_2: "VE", iso3166_3: "VEN", destatisBevCode: Integer.parseInt("367")))
    nations.add(new Nation(searchTerm: "Vereinigte Arabische Emirate", officialTermShort: "Vereinigte Arabische Emirate", officialTermLong: "die Vereinigten Arabischen Emirate (Abu Dhabi, Adschman, Dubai, Fudschaira, Ras al Chaima, Schardscha, Umm al Kaiwain)", citizenship: "der Vereinigten Arabischen Emirate", continent: Continent.ASI, iso3166_2: "AE", iso3166_3: "ARE", destatisBevCode: Integer.parseInt("469")))
    nations.add(new Nation(searchTerm: "Vereinigte Staaten", officialTermShort: "Vereinigte Staaten", officialTermLong: "die Vereinigten Staaten von Amerika", citizenship: "amerikanisch", continent: Continent.AME, iso3166_2: "US", iso3166_3: "USA", destatisBevCode: Integer.parseInt("368")))
    nations.add(new Nation(searchTerm: "Vereinigtes Königreich", officialTermShort: "Vereinigtes Königreich", officialTermLong: "das Vereinigte Königreich Großbritannien und Nordirland", citizenship: "britisch", continent: Continent.EUR, iso3166_2: "GB", iso3166_3: "GBR", destatisBevCode: Integer.parseInt("168")))
    nations.add(new Nation(searchTerm: "Vietnam", officialTermShort: "Vietnam", officialTermLong: "die Sozialistische Republik Vietnam", citizenship: "vietnamesisch", continent: Continent.ASI, iso3166_2: "VN", iso3166_3: "VNM", destatisBevCode: Integer.parseInt("432")))
    nations.add(new Nation(searchTerm: "Zentralafrikanische Republik", officialTermShort: "Zentralafrikanische Republik", officialTermLong: "die Zentralafrikanische Republik", citizenship: "zentralafrikanisch", continent: Continent.AFR, iso3166_2: "CF", iso3166_3: "CAF", destatisBevCode: Integer.parseInt("289")))
    nations.add(new Nation(searchTerm: "Zypern", officialTermShort: "Zypern", officialTermLong: "die Republik Zypern", citizenship: "zyprisch", continent: Continent.EUR, iso3166_2: "CY", iso3166_3: "CYP", destatisBevCode: Integer.parseInt("181")))
    // END Autogenerated

    // Set EU-Flag. Source: https://ec.europa.eu/eurostat/statistics-explained/pdfscache/4904.pdf
    final Set<String> euCodes = ["BE", "BG", "CZ", "DK", "DE", "EE", "IE", "EL", "ES", "FR", "HR",
                                 "IT", "CY", "LV", "LT", "LU", "HU", "MT", "NL", "AT", "PL", "PT",
                                 "RO", "SI", "SK", "FI", "SE"]
    nations.each { it.isEu = euCodes.contains(it.iso3166_2) }

    return nations.asImmutable()
  }
}
